const dat = {
    "CustomerDetails": {
        "firstName": "",
        "lastName": "",
        "mobileNo": "",
        "email": "",
        "customerType": "CUSTOMER_INDIVIDUAL",
        "GSTIN": "",
        "aadharNumber": "--",
        "dateOfBirth": "",
        "address1": "",
        "address2": "",
        "address3": "",
        "areaCode": "",
        "areaName": "",
        "cityCode": "",
        "cityName": "",
        "stateName": "",
        "stateCode": "",
        "pinCode": "",
        "panNumber": ""
    },
    "QuotationData": {
        "quoteNo": "QPCCOD0000180219",
        "renewalPolicyNo": "",
        "lineOfBusiness": "MOTOR",
        "subLine": "Private Car",
        "productCode": "PCCOD",
        "productName": "PCC_OWNDAMAGE",
        "businessType": "RollOver",
        "policyStartDate": "11/01/2024",
        "expiryDate": "10/01/2025",
        "userId": "SRINVAS",
        "isVipPolicy": "N",
        "channelType": "POS",
        "branchName": "",
        "branchCode": "",
        "quoteStatus": "QUOTE",
        "insurerCode": "114",
        "insurerName": "",
        "intgQuotationNo": "",
        "policyTenure": "1",
        "cpaTenure": "1",
        "newBusinessOdTp": "",
        "odExpiryDate": "",
        "tpExpiryDate": "",
        "parentUserId": "saravanan@12",
        "walletType": "",
        "isCPADeclaration": "No valid driving license",
        "shortfallPercent": "0.0",
        "revisedDiscountRt": "0",
        "PreviousPolicyDetails": {
            "prevPolicyNo": "",
            "prevPolicyExp": "03/01/2024",
            "prevPolicyNcb": "25",
            "prevPolicyInsurerCode": "104",
            "prevPolicyInsurerName": "BAJAJ ALLIANZ GENERAL INSURANCE CO. LTD.",
            "isPrevPolicyClaim": "N",
            "prevPolicyType": "COMPREHENSIVE",
            "prevPolicyODExpireDate": "03/01/2024",
            "prevPolicyTPExpireDate": "16/01/2024",
            "prevPolicyTPStartDate": "10/01/2024"
        }
    },
    "VehicleDetails": {
        "engineNo": "",
        "chassisNo": "",
        "registrationNo": "TN-12-ER-1244",
        "yearOfMfg": 2021,
        "registrationDate": "05/01/2021",
        "makeCode": "AUD",
        "modelCode": "MD000021",
        "makeName": "AUDI",
        "modelName": "A7",
        "subModelName": "3.0 TDI SPORTBACK",
        "subModelCode": "SM00000150",
        "engineCC": "2967",
        "fuelType": "PETROL",
        "rtoCode": "TN12",
        "rtoName": "CHENNAI POONAMALLEE",
        "actualIdv": 0,
        "vehicleAge": 3.02,
        "seatingCapacity": "5",
        "cubicCapacity": "2967",
        "zone": "ZONE A",
        "currentNCB": "35",
        "isInBuilt": "false",
        "isCarOwnerChanged": "N",
        "isUsedToVehicle": "N",
        "istrailerneed": "",
        "rtoNo": "TN12",
        "rtoRegistration": "CHENNAI POONAMALLEE",
        "showRoomPrice": 0,
        "carrierType": "",
        "usageType": "",
        "noOfTraillers": "",
        "trailerIdvDto": [],
        "vehicleType": "OTHER THAN THREE WHEELER",
        "regiCityCode": "",
        "regiCityName": "CHENNAI",
        "grossVehicleWeight": "null"
    },
    "CoverDetails": [],
    "InsurerDetails": [
        {
            "insurerCode": "114",
            "idv": 0,
            "minIdv": 0,
            "maxIdv": 0,
            "originalIdv": 0,
            "planName": "",
            "tariffDis": "0"
        }
    ]
}
export default dat;